// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: encoding.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *Test1) Reset() {
	*x = Test1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1) ProtoMessage() {}

func (x *Test1) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1.ProtoReflect.Descriptor instead.
func (*Test1) Descriptor() ([]byte, []int) {
	return file_encoding_proto_rawDescGZIP(), []int{0}
}

func (x *Test1) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

var File_encoding_proto protoreflect.FileDescriptor

var file_encoding_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x69, 0x6d, 0x70, 0x6c, 0x22, 0x15, 0x0a, 0x05, 0x54, 0x65, 0x73, 0x74, 0x31, 0x12,
	0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x42, 0x1e, 0x5a,
	0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6d, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encoding_proto_rawDescOnce sync.Once
	file_encoding_proto_rawDescData = file_encoding_proto_rawDesc
)

func file_encoding_proto_rawDescGZIP() []byte {
	file_encoding_proto_rawDescOnce.Do(func() {
		file_encoding_proto_rawDescData = protoimpl.X.CompressGZIP(file_encoding_proto_rawDescData)
	})
	return file_encoding_proto_rawDescData
}

var file_encoding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_encoding_proto_goTypes = []any{
	(*Test1)(nil), // 0: impl.Test1
}
var file_encoding_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encoding_proto_init() }
func file_encoding_proto_init() {
	if File_encoding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encoding_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Test1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encoding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encoding_proto_goTypes,
		DependencyIndexes: file_encoding_proto_depIdxs,
		MessageInfos:      file_encoding_proto_msgTypes,
	}.Build()
	File_encoding_proto = out.File
	file_encoding_proto_rawDesc = nil
	file_encoding_proto_goTypes = nil
	file_encoding_proto_depIdxs = nil
}
